map:
  integer: 1234
  float: 3.14159
  string: "string"
  boolean: true
  list:
    - true
    - "string"
    - 3.14159
    - 1234
  map:
      integer: 1234
      float: 3.14159
      string: "string"
      boolean: true
